METADATADIR = metadata
GIRDIR = gir

wireplumber-0.5:
	vapigen \
		--pkg gio-2.0 \
		--library=wireplumber-0.5 \
		--metadatadir $(METADATADIR) \
		$(METADATADIR)/Wp-0.5-custom.vala \
		$(GIRDIR)/Wp-0.5.gir
